apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
    - name: redis
      image: quay.io/sameersbn/redis
      ports:
        - containerPort: 6379
          protocol: TCP
